name: Compilacion .NET

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restaurar y Compilar automaticamente
      shell: pwsh
      run: |
        $solucion = Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object -First 1
        if ($solucion) {
            Write-Host "¡Solución encontrada en: $($solucion.FullName)!"
            nuget restore $solucion.FullName
            msbuild $solucion.FullName /p:Configuration=Release
        } else {
            Write-Error "No se encontró ningún archivo .sln en el repositorio."
        }
