name: Compilacion .NET

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restaurar y Compilar automaticamente
      shell: pwsh
      run: |
        $proyecto = Get-ChildItem -Path . -Filter *.csproj -Recurse | Select-Object -First 1
        if ($proyecto) {
            Write-Host "¡Proyecto encontrado en: $($proyecto.FullName)!"
            nuget restore $proyecto.FullName
            msbuild $proyecto.FullName /p:Configuration=Release
        } else {
            Write-Error "Error grave: Tampoco se encontró el archivo .csproj. Visual Studio no subió tu código a GitHub."
        }
